apiVersion: v1
kind: Pod
metadata:
  name: aplicacion-web-estatica2
  labels:
    role: admin
spec:
  containers:
    - name: web
      image: lgracia/dev:testnode
      ports:
        - name: web
          containerPort: 5000
          protocol: TCP