apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: default
  labels:
    app: frontend
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "CORSALLOWCREDENTIALS"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, PATCH"
    nginx.ingress.kubernetes.io/cors-allow-origin: "CORSALLOWORIGIN"
    nginx.ingress.kubernetes.io/configuration-snippet: |
          add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload";
spec:
  tls:
  - hosts:
      - DOMAIN
    secretName: SECRETTLS
  rules:
  - host: DOMAIN
    http:
      paths:
      - backend:
          service:
            name: frontend
            port:
              number: 80
        path: /
        pathType: Prefix
  ingressClassName: nginx