apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-path
spec:
  ingressClassName: nginx
  rules:
    - host: path.example.com
      http:
        - path: /v1/hello
          pathType: Exact
          backend:
            service:
              name: hello-world-clusterip
              port: 
                number: 80
